"""add analytics models

Revision ID: 57bf76980370
Revises: initial
Create Date: 2026-06-25 22:07:55.182094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57bf76980370'
down_revision = 'initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productivity_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('productivity_score', sa.Float(), nullable=False),
    sa.Column('focus_score', sa.Float(), nullable=False),
    sa.Column('consistency_score', sa.Float(), nullable=False),
    sa.Column('discipline_score', sa.Float(), nullable=False),
    sa.Column('deep_work_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_date_score')
    )
    with op.batch_alter_table('productivity_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productivity_scores_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_productivity_scores_user_id'), ['user_id'], unique=False)

    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_blocklist_user_id'), ['user_id'], unique=False)

    op.create_table('behavior_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('metadata_obj', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('behavior_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_behavior_events_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_behavior_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_behavior_events_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_behavior_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_behavior_events_upload_id'), ['upload_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_behavior_events_user_id'), ['user_id'], unique=False)

    op.create_table('behavior_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Float(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('productivity_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('behavior_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_behavior_sessions_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_behavior_sessions_session_type'), ['session_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_behavior_sessions_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_behavior_sessions_upload_id'), ['upload_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_behavior_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_generated_at'), ['generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_report_type'), ['report_type'], unique=False)

    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('stored_filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('mime_type', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Enum('uploaded', 'processing', 'completed', 'failed', name='upload_status_enum'), nullable=False))
        batch_op.add_column(sa.Column('upload_source', sa.String(length=50), nullable=False))
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_uploads_original_filename'), ['original_filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploads_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploads_stored_filename'), ['stored_filename'], unique=True)
        batch_op.create_index(batch_op.f('ix_uploads_upload_date'), ['upload_date'], unique=False)
        batch_op.drop_column('file_name')
        batch_op.drop_column('file_type')
        batch_op.drop_column('processing_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_status', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('file_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('file_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_index(batch_op.f('ix_uploads_upload_date'))
        batch_op.drop_index(batch_op.f('ix_uploads_stored_filename'))
        batch_op.drop_index(batch_op.f('ix_uploads_status'))
        batch_op.drop_index(batch_op.f('ix_uploads_original_filename'))
        batch_op.alter_column('file_size',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('upload_source')
        batch_op.drop_column('status')
        batch_op.drop_column('upload_date')
        batch_op.drop_column('mime_type')
        batch_op.drop_column('stored_filename')
        batch_op.drop_column('original_filename')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_reports_generated_at'))

    with op.batch_alter_table('behavior_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_behavior_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_behavior_sessions_upload_id'))
        batch_op.drop_index(batch_op.f('ix_behavior_sessions_start_time'))
        batch_op.drop_index(batch_op.f('ix_behavior_sessions_session_type'))
        batch_op.drop_index(batch_op.f('ix_behavior_sessions_end_time'))

    op.drop_table('behavior_sessions')
    with op.batch_alter_table('behavior_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_behavior_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_behavior_events_upload_id'))
        batch_op.drop_index(batch_op.f('ix_behavior_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_behavior_events_source'))
        batch_op.drop_index(batch_op.f('ix_behavior_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_behavior_events_category'))

    op.drop_table('behavior_events')
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_user_id'))
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    with op.batch_alter_table('productivity_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productivity_scores_user_id'))
        batch_op.drop_index(batch_op.f('ix_productivity_scores_date'))

    op.drop_table('productivity_scores')
    # ### end Alembic commands ###
